# Generated by Django 5.2.4 on 2025-10-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'รายการอาหาร', 'verbose_name_plural': 'รายการอาหาร'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='เมนูแนะนำพิเศษ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('MAIN', 'อาหารจานหลัก'), ('SEAFOOD', 'อาหารทะเล'), ('DESSERT', 'ของหวาน'), ('DRINK', 'เครื่องดื่ม')], default='MAIN', max_length=10, verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบาย'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='รูปภาพอาหาร'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่ออาหาร'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ราคา (บาท)'),
        ),
    ]
