# Generated by Django 5.2.4 on 2025-10-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_options_remove_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'หมวดหมู่', 'verbose_name_plural': 'หมวดหมู่'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='พร้อมจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=1, verbose_name='คำอธิบาย'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่ออาหาร'),
        ),
    ]
