# Generated by Django 5.2.4 on 2025-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ชื่อรูปภาพ/คำบรรยายสั้น')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='รูปภาพแกลเลอรี')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('is_visible', models.BooleanField(default=True, verbose_name='แสดงผลในหน้าเว็บ')),
            ],
            options={
                'verbose_name': 'รูปภาพแกลเลอรี',
                'verbose_name_plural': 'รูปภาพแกลเลอรี',
                'ordering': ['order', 'title'],
            },
        ),
    ]
