# Generated by Django 5.2.4 on 2025-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อผู้จอง')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล (ถ้ามี)')),
                ('date', models.DateField(verbose_name='วันที่จอง')),
                ('time', models.TimeField(verbose_name='เวลาจอง')),
                ('party_size', models.IntegerField(verbose_name='จำนวนคน')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='คำขอพิเศษ')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='ยืนยันแล้ว')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='จองเมื่อ')),
            ],
            options={
                'verbose_name': 'การจองโต๊ะ',
                'verbose_name_plural': 'การจองโต๊ะ',
                'ordering': ['date', 'time'],
            },
        ),
    ]
