# Generated by Django 5.2.4 on 2025-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time'], 'verbose_name': 'การจอง/สั่ง', 'verbose_name_plural': 'การจอง/สั่ง'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_takeaway',
            field=models.BooleanField(default=False, verbose_name='สั่งกลับบ้าน'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนคน (ถ้าจองโต๊ะ)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างรายการเมื่อ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='เวลา'),
        ),
    ]
