# Generated by Django 5.2.4 on 2025-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_reservation_options_reservation_is_takeaway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assigned_table',
            field=models.CharField(blank=True, choices=[('T1', 'โต๊ะที่ 1'), ('T2', 'โต๊ะที่ 2'), ('T3', 'โต๊ะที่ 3'), ('T4', 'โต๊ะที่ 4'), ('T5', 'โต๊ะที่ 5'), ('T6', 'โต๊ะที่ 6'), ('T7', 'โต๊ะที่ 7'), ('T8', 'โต๊ะที่ 8'), ('T9', 'โต๊ะที่ 9'), ('T10', 'โต๊ะที่ 10'), ('T11', 'โต๊ะที่ 11'), ('T12', 'โต๊ะที่ 12'), ('T13', 'โต๊ะที่ 13'), ('T14', 'โต๊ะที่ 14'), ('T15', 'โต๊ะที่ 15')], max_length=5, null=True, verbose_name='หมายเลขโต๊ะที่จัดสรร'),
        ),
    ]
