# Generated by Django 5.2.4 on 2025-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_reservation_assigned_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(choices=[('T1', 'โต๊ะที่ 1'), ('T2', 'โต๊ะที่ 2'), ('T3', 'โต๊ะที่ 3'), ('T4', 'โต๊ะที่ 4'), ('T5', 'โต๊ะที่ 5'), ('T6', 'โต๊ะที่ 6'), ('T7', 'โต๊ะที่ 7'), ('T8', 'โต๊ะที่ 8'), ('T9', 'โต๊ะที่ 9'), ('T10', 'โต๊ะที่ 10'), ('T11', 'โต๊ะที่ 11'), ('T12', 'โต๊ะที่ 12'), ('T13', 'โต๊ะที่ 13'), ('T14', 'โต๊ะที่ 14'), ('T15', 'โต๊ะที่ 15')], max_length=5, unique=True, verbose_name='หมายเลขโต๊ะ')),
                ('capacity', models.IntegerField(default=4, verbose_name='ความจุสูงสุด (คน)')),
                ('current_status', models.CharField(choices=[('A', 'ว่าง (Available)'), ('O', 'ไม่ว่าง (Occupied)'), ('R', 'จองแล้ว (Reserved)'), ('C', 'ปิดปรับปรุง (Closed)')], default='A', max_length=1, verbose_name='สถานะปัจจุบัน')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
            ],
            options={
                'verbose_name': 'สถานะโต๊ะ',
                'verbose_name_plural': 'สถานะโต๊ะ',
                'ordering': ['table_number'],
            },
        ),
    ]
