"""
Django settings for RestaurantProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/#__file__
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vhj&^uxg883r)f615cj)=uolg5&1m@sty!2-z%bip9%@)2rdme'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin', # ⭐️ ต้องอยู่ก่อน admin ⭐️
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'menu',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RestaurantProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # แก้ไข: ลบ DIRS: [] ที่ซ้ำซ้อน 
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'RestaurantProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th' # ⭐️ เปลี่ยนเป็นภาษาไทย ⭐️

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# ⭐️ เพิ่ม STATIC_ROOT เพื่อแก้ปัญหา collectstatic ⭐️
STATIC_ROOT = BASE_DIR / 'staticfiles'


# **การตั้งค่าสำหรับ Media Files (รูปภาพที่ผู้ใช้อัปโหลด)**
# URL ที่ใช้เข้าถึงไฟล์ Media ผ่านเว็บเบราว์เซอร์
MEDIA_URL = '/media/'
# ตำแหน่งจริงบนระบบไฟล์ที่ Django จะเก็บไฟล์ Media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_uploads')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------------------------------------------------------------
# ⭐️ JAZZMIN SETTINGS (รวมและปรับปรุง): ตกแต่ง Admin ให้สวยงามและใช้งานง่าย ⭐️
# -------------------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # 1. แบรนด์และข้อความต้อนรับ
    "site_brand": "THAI FOOD 🌶️",
    "site_header": "Restaurant Management",
    "welcome_sign": "ยินดีต้อนรับสู่ระบบจัดการร้านอาหารไทย (Admin)",
    
    # 2. สีสันและธีม
    "theme": "yeti", # ใช้ theme 'yeti' เพื่อให้พื้นหลังขาวสะอาดตา ตัดกับสีส้ม
    "navbar_color": "navbar-dark bg-amber-600",
    "primary": "orange", # 'orange' จะให้สีส้มที่สว่างและเด่นชัด
    
    # 3. การกำหนดไอคอน (ทำให้เมนูใน Sidebar ดูดีขึ้น)
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "menu.Category": "fas fa-utensils",       # หมวดหมู่อาหาร
        "menu.MenuItem": "fas fa-hamburger",      # รายการอาหาร
        "menu.GalleryImage": "fas fa-image",      # แกลเลอรีภาพ
        "menu.Reservation": "fas fa-calendar-check", # การจอง/สั่ง
        "menu.Table": "fas fa-chair",             # สถานะโต๊ะ
    },
    
    # 4. การจัดกลุ่มเมนูใน Sidebar (ทำให้เป็นหมวดหมู่)
    "order_with_respect_to": [
        "menu.Reservation",
        "menu.Table",
        "menu.Category",
        "menu.MenuItem",
        "menu.GalleryImage",
        "auth.User",
        "auth.Group",
    ],

    # 5. Top Menu Links (ทางลัด)
    "topmenu_links": [
        {"name": "ดูเว็บไซต์", "url": "home", "new_window": True, "icon": "fas fa-globe"},
        {"model": "menu.Reservation", "icon": "fas fa-calendar-alt"}, 
        {"name": "จัดการผู้ใช้", "url": "auth:user:changelist", "permissions": ["auth.view_user"]}, 
    ],
    
    # 6. UI Tweaks (ปรับปรุงรูปลักษณ์)
    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
}

# -------------------------------------------------------------
# ⭐️ JAZZMIN UI TWEAKS: ปรับ UI ให้คมชัดและเข้ากัน ⭐️
# -------------------------------------------------------------
JAZZMIN_UI_TWEAKS = {
    # ⭐️ body_small_text: False ทำให้ขนาดตัวอักษรเป็นมาตรฐาน (ใหญ่ขึ้น) ⭐️
    "body_small_text": False, 
    "navbar_small_text": False,
    "footer_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-orange", 
    "navbar": "navbar-dark navbar-amber", 
    "no_navbar_border": False,
    "navbar_fixed": True, 
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True, 
    "sidebar": "sidebar-light-primary", 
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_style": "accordion",
    "theme": "yeti", 
    "button_classes": {
        "primary": "btn-primary", # ใช้ primary เพื่อให้ปุ่มหลักเป็นสีส้ม/อำพันชัดเจน
        "secondary": "btn-outline-secondary",
    }
}

# -------------------------------------------------------------
# ⭐️ LINE MESSAGING API SETTINGS ⭐️
# -------------------------------------------------------------
# 1. Channel Access Token (Long-lived)
LINE_CHANNEL_ACCESS_TOKEN = 'xFlRW/l24qogv6sLQVRU4Kt8tGLvxUEH/4ZRf12aDFs6wfFVjKCWreev3YLAaSoqQySrrJjKoxU+4JtEbdoSPW4nEUV+fP+PWVZcf7NYHFTDYFNJsp9YXOjIjXMO25VVkCpiqw6lMTgt/aiRqAPGBQdB04t89/1O/w1cDnyilFU=' 

# 2. Channel Secret
LINE_CHANNEL_SECRET = 'd53edf135a8020effca73d45c2012b23' 

# 3. Notification Target ID (User ID หรือ Group ID ที่ต้องการให้ข้อความเข้า)
# - User ID จะขึ้นต้นด้วย Uxxx...
# - Group ID จะขึ้นต้นด้วย Cxxx...
LINE_NOTIFICATION_TARGET_ID = 'U7097fa6d013a977b0daec5d5d18d15cd' 
# **สำคัญ:** ห้ามแชร์ Token/Secret นี้ให้คนอื่นโดยเด็ดขาด